/*
 * Swagger Forex Service - OpenAPI 3.0
 *
 * This service provides api's needed to perform operation against forex reference data
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package response

type ConversionResponse struct {
	// The initial amount
	Amount float64 `json:"amount,omitempty"`
	// The converted amount
	ConvertedAmount float64 `json:"convertedAmount,omitempty"`
	// The source currency code
	BaseCurrency string `json:"baseCurrency,omitempty"`
	// The target currency code
	TargetCurrency string `json:"targetCurrency,omitempty"`
	// Timestamp when the conversion was initiated(Epoch time)
	InitiatedOn int64 `json:"initiatedOn,omitempty"`
	// Timestamp when the conversion was initiated(Epoch time)
	TimeTaken    int64  `json:"timeTaken,omitempty"`
	ReceivedTime int64  `json:"receivedTime,omitempty"`
	HostName     string `json:"hostName,omitempty"`
	// The conversion rate
	Rate float64 `json:"rate,omitempty"`
}
